name: Package and publish Netflix conductor container

on:
  push:
      branches:
        - main
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "PRECHECK"
        ls -lrthS

    - name: GET FROM NETFLIX
      uses: actions/checkout@v3
      with:
        # repository: Netflix/conductor
        repository: s50600822/conductor
        token: ${{ secrets.PAT }}
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        # Default: 1
        # fetch-depth: 0

    # - run: |
    #     echo "REMOVING package-lock.json because it's kind of retarded!"
    #     rm -rfv ui/package-lock.json
    #     ls -lrthS
    
    #https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    - name: LOGIN DOCKERHUB
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: BUILD CONTAINER
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        #context: docker/serverAndUI
        context: .
        file: docker/serverAndUI/Dockerfile
        tags: s50600822/conductor-su:latest
        load: true
    
    - name: PUBLISH
      run: docker push s50600822/conductor-su:latest